"""Shared helpers for integration tests."""

from __future__ import annotations

import contextlib
import io
from typing import Iterator

from create_dlthub_workspace.scaffold import AGENT_FILES, SCAFFOLDS_DIR


@contextlib.contextmanager
def silenced() -> Iterator[None]:
    """Suppress stdout + stderr noise from rich.console panels during tests."""
    with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
        yield


def scaffold_has_ai_files(scaffold: str = "starter_workspace") -> bool:
    """True iff the bundled scaffold already includes the AI workbench files.

    AI files are generated by `make generate-ai` and committed. Until that's
    been done, e2e tests that assert on AI file presence skip with a hint.
    """
    scaffold_dir = SCAFFOLDS_DIR / scaffold
    # The `.agents/` directory is the broadest marker — it's always populated
    # by a real generate-ai run regardless of which agents are selected.
    return (scaffold_dir / ".agents").is_dir()


# Files we expect to find at the workspace root after a real `create-dlthub-workspace
# --yes` run, organized by agent so individual tests can assert on subsets.
EXPECTED_AGENT_ROOT_ENTRIES = AGENT_FILES
